# Build react application 
FROM node:16.19-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/
RUN yarn --silent
COPY . /app
ARG REACT_APP_HTTP_TIMEOUT
ENV REACT_APP_HTTP_TIMEOUT $REACT_APP_HTTP_TIMEOUT
ARG REACT_APP_MAX_FILE_SIZE
ENV REACT_APP_MAX_FILE_SIZE $REACT_APP_MAX_FILE_SIZE
ARG REACT_APP_AUTH_COOKIE
ENV REACT_APP_AUTH_COOKIE $REACT_APP_AUTH_COOKIE
ARG REACT_APP_MAPBOX_TOKEN
ENV REACT_APP_MAPBOX_TOKEN $REACT_APP_MAPBOX_TOKEN
ARG REACT_APP_GOOGLE_ANALYTICS_ID
ENV REACT_APP_GOOGLE_ANALYTICS_ID $REACT_APP_GOOGLE_ANALYTICS_ID
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL $REACT_APP_API_URL
ARG REACT_APP_CMS_URL
ENV REACT_APP_CMS_URL $REACT_APP_CMS_URL
ARG REACT_APP_CMS_HOME_1_ID
ENV REACT_APP_CMS_HOME_1_ID $REACT_APP_CMS_HOME_1_ID
ARG REACT_APP_CMS_HOME_2_ID
ENV REACT_APP_CMS_HOME_2_ID $REACT_APP_CMS_HOME_2_ID
ARG REACT_APP_CMS_HOME_3_ID
ENV REACT_APP_CMS_HOME_3_ID $REACT_APP_CMS_HOME_3_ID
ARG REACT_APP_CMS_HOME_4_ID
ENV REACT_APP_CMS_HOME_4_ID $REACT_APP_CMS_HOME_4_ID
ARG REACT_APP_CMS_ABOUT_ID
ENV REACT_APP_CMS_ABOUT_ID $REACT_APP_CMS_ABOUT_ID
ARG REACT_APP_CMS_PRIVACY_POLICY_ID
ENV REACT_APP_CMS_PRIVACY_POLICY_ID $REACT_APP_CMS_PRIVACY_POLICY_ID
ARG REACT_APP_CMS_WHAT_IS_ID
ENV REACT_APP_CMS_WHAT_IS_ID $REACT_APP_CMS_WHAT_IS_ID
RUN yarn build

# Copy files and launch image
FROM nginx:1.23.3-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
